import { Inter } from "next/font/google";
import "./globals.css";
import HeaderMenu from "./components/layouts/HeaderMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Flutter-Newbie Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <HeaderMenu />
        {children}
      </body>
    </html>
  );
}
